<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-08-13T23:37:49 IST" name="Default suite" finished-at="2025-08-13T23:37:49 IST" duration-ms="22">
    <groups>
    </groups>
    <test started-at="2025-08-13T23:37:49 IST" name="Default test" finished-at="2025-08-13T23:37:49 IST" duration-ms="22">
      <class name="testCases.TC002LoginWithInvalidDetailsTest">
        <test-method is-config="true" signature="startReport()[pri:0, instance:testCases.TC002LoginWithInvalidDetailsTest@26bbe604]" started-at="2025-08-13T23:37:49 IST" name="startReport" finished-at="2025-08-13T23:37:49 IST" duration-ms="115" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startReport -->
        <test-method is-config="true" signature="testcaseDetails()[pri:0, instance:testCases.TC002LoginWithInvalidDetailsTest@26bbe604]" started-at="2025-08-13T23:37:49 IST" name="testcaseDetails" finished-at="2025-08-13T23:37:49 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcaseDetails -->
        <test-method is-config="true" signature="detail()[pri:0, instance:testCases.TC002LoginWithInvalidDetailsTest@26bbe604]" started-at="2025-08-13T23:37:49 IST" name="detail" finished-at="2025-08-13T23:37:49 IST" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- detail -->
        <test-method signature="TC002_LoginTest(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:testCases.TC002LoginWithInvalidDetailsTest@26bbe604]" started-at="2025-08-13T23:37:49 IST" name="TC002_LoginTest" data-provider="LoginData" finished-at="2025-08-13T23:37:49 IST" duration-ms="0" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.hssf.usermodel.HSSFSheet.getLastRowNum()" because "utility.UtilClass.sheet" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "org.apache.poi.hssf.usermodel.HSSFSheet.getLastRowNum()" because "utility.UtilClass.sheet" is null
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:58)
at org.testng.internal.invokers.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:159)
at org.testng.internal.Parameters.handleParameters(Parameters.java:809)
at org.testng.internal.Parameters.handleParameters(Parameters.java:734)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:949)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.poi.hssf.usermodel.HSSFSheet.getLastRowNum()" because "utility.UtilClass.sheet" is null
at utility.UtilClass.getRowCount(UtilClass.java:222)
at testCases.TC002LoginWithInvalidDetailsTest.getLoginData(TC002LoginWithInvalidDetailsTest.java:52)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:54)
... 25 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC002_LoginTest -->
        <test-method is-config="true" signature="flushReport()[pri:0, instance:testCases.TC002LoginWithInvalidDetailsTest@26bbe604]" started-at="2025-08-13T23:37:49 IST" name="flushReport" finished-at="2025-08-13T23:37:50 IST" duration-ms="362" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flushReport -->
      </class> <!-- testCases.TC002LoginWithInvalidDetailsTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
